# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
plugins:
  - jekyll-redirect-from
title: Leiden ITP
tagline: tagline
description: description
author: Josh Hug
baseurl: '/calendar' # the subpath of your site, e.g. /blog
url: 'https://joshhug.github.io/leidenITP2/' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.6.2
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Brightspace:
    - 'https://brightspace.universiteitleiden.nl/d2l/home/240322'

footer_content:

# Collections for website data
collections:
  modules:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module


compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
